# Generated by Django 4.0.5 on 2022-06-21 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snsapp', '0005_alter_freecomment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='mainphoto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
