# Generated by Django 4.0.5 on 2022-06-21 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snsapp', '0006_post_mainphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='clothes',
            field=models.CharField(blank=True, choices=[('S', 'Shirt'), ('P', 'Pants'), ('A', 'Accessories')], max_length=15),
        ),
    ]
