# Generated by Django 4.0.5 on 2022-06-21 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snsapp', '0007_comment_clothes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='clothes',
            field=models.CharField(choices=[('S', 'Shirt'), ('P', 'Pants'), ('A', 'Accessories')], max_length=15),
        ),
    ]
