# Generated by Django 4.0.5 on 2022-06-21 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snsapp', '0010_post_cloth_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cloth_type',
            field=models.CharField(choices=[('Ds', 'Dresses'), ('BlouShir', 'Blouses & Shirts'), ('Cts', 'Coats'), ('Bmbrs', 'Bombers'), ('Tshrts', 'T-shirts & Tops'), ('Sweat', 'Sweatshirts'), ('Car', 'Cardigans & Sweaters'), ('Jckt', 'Jackets'), ('Trou', 'Trousers'), ('Je', 'Jeans'), ('Shrts', 'Shorts'), ('Skrts', 'Skirts'), ('Night', 'Nightwear'), ('Underwear', 'Underwear')], default='', max_length=20),
        ),
    ]
