# Generated by Django 4.0.5 on 2022-06-22 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snsapp', '0011_alter_post_cloth_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='body',
        ),
        migrations.AddField(
            model_name='post',
            name='drycleaning',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='repair',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='season',
            field=models.CharField(choices=[('SS', 'SS'), ('FW', 'FW')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='size',
            field=models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='temperature',
            field=models.CharField(choices=[('30', '30'), ('40', '40'), ('50', '50'), ('60', '60')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='washType',
            field=models.CharField(choices=[('1', 'doNotWash'), ('2', ''), ('3', ''), ('4', '')], default='', max_length=20),
        ),
    ]
