# Generated by Django 4.0.4 on 2022-06-22 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snsapp', '0014_alter_post_drycleaning_alter_post_repair'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freecomment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='freepost',
            name='author',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='FreeComment',
        ),
        migrations.DeleteModel(
            name='FreePost',
        ),
    ]
